status.samryetha.com {
	import security_headers
	encode gzip
	header Cache-Control "no-store"
	handle /update* {
		reverse_proxy 127.0.0.1:3030
	}
	handle /api/update* {
		reverse_proxy 127.0.0.1:3030
	}
	handle {
		root * /opt/Samryetha/status/www
		file_server
	}
}
